require: sudo
language: node_js
services:
  - docker
script: 
  docker build -t api-detran .
deploy:
  provider: script
  script: docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push api-detran
  on:
    branch: master
